baseURL = 'https://www.chipsalliance.org/'
languageCode = 'en-us'
title = 'CHIPS Alliance'

buildFuture = true 

[markup.goldmark.renderer]
unsafe= true

googleAnalytics = 'G-H0KF2YZTR7'

[params]
  description = 'CHIPS (Common Hardware for Interfaces, Processors and Systems) Alliance harnesses the energy of open source collaboration to accelerate hardware development.'
  images = ['images/chips-alliance-share.jpg']
  title = 'CHIPS Alliance'

[social]
  twitter = 'chipsalliance'

[module]
  [[module.imports]]
    path = "github.com/chipsalliance/tsc"

  [[module.imports.mounts]]
    source = "workgroups"
    target = "content/workgroups"
